### ISSUE TITLE
Erro crítico quando a transação fica em análise pelo PagSeguro no cartão de crédito

### ISSUE THREAD

**Issue by tiago-sartor** [pagseguro/pagbank-for-woocommerce#31]
Olá,

Está ocorrendo um erro crítico para compras efetuadas no cartão e que ficam em análise pelo PagSeguro. Um cliente efetuou 3 pedidos conosco, todos no cartão. O primeiro foi aprovado instantaneamente e não teve nenhum erro, os outros dois ficaram em análise pelo PagSeguro (e no WooCommerce ficaram registrados com o status "Aguardando Pagamento"). Os pagamentos em análise foram aprovados com sucesso, porém os pedidos permaneceram com status "Aguardando Pagamento" no WooCommerce. Eu precisei alterar manualmente o status para "Processando" e foi nesse momento que ocorreu o erro crítico no Wordpress.

Detalhes do erro:
`Mensagem
PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /srv/htdocs/wp-content/plugins/pagbank-for-woocommerce/src/core/Presentation/Hooks.php:150
Stack trace:
#0 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(326): PagBank_WooCommerce\Presentation\Hooks->filter_woocommerce_get_order_item_totals(Array, Object(WC_Order))
#1 /wordpress/core/6.6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(2338): apply_filters('woocommerce_get...', Array, Object(WC_Order), 'excl')
#3 /srv/htdocs/wp-content/plugins/yaymail/includes/MailBuilder/Shortcodes.php(955): WC_Order->get_order_item_totals()
#4 /srv/htdocs/wp-content/plugins/yaymail/includes/MailBuilder/Shortcodes.php(420): YayMail\MailBuilder\Shortcodes->collectOrderData(false, Array)
#5 /srv/htdocs/wp-content/plugins/yaymail/views/templates/single-mail-template.php(124): YayMail\MailBuilder\Shortcodes->shortCodesOrderDefined(false, Array)
#6 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#7 /srv/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functions.php(364): wc_get_template('emails/customer...', Array, '', '')
#8 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php(113): wc_get_template_html('emails/customer...', Array)
#9 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(588): WC_Email_Customer_Processing_Order->get_content_html()
#10 /srv/htdocs/wp-content/plugins/woocommerce/includes/emails/class-wc-email-customer-processing-order.php(93): WC_Email->get_content()
#11 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): WC_Email_Customer_Processing_Order->trigger(18016, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#12 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#13 /wordpress/core/6.6.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-emails.php(172): do_action_ref_array('woocommerce_ord...', Array)
#15 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): WC_Emails::send_transactional_email(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#16 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#17 /wordpress/core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(420): do_action('woocommerce_ord...', 18016, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#19 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(253): WC_Order->status_transition()
#20 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-order.php(365): WC_Order->save()
#21 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(585): WC_Order->update_status('processing', '', true)
#22 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(324): WC_AJAX::mark_order_status('')
#23 /wordpress/core/6.6.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#24 /wordpress/core/6.6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#25 /wordpress/core/6.6.2/wp-admin/admin-ajax.php(192): do_action('wp_ajax_woocomm...')
#26 {main}
  thrown in /srv/htdocs/wp-content/plugins/pagbank-for-woocommerce/src/core/Presentation/Hooks.php on line 150
Marca temporal
2024-11-11T13:00:49.000Z
Tipo
plugins
Nome
pagbank-for-woocommerce
Arquivo
/srv/htdocs/wp-content/plugins/pagbank-for-woocommerce/src/core/Presentation/Hooks.php
Linha
150`

Outra questão que eu notei e que pode estar relacionada: no site do PagBank o pagamento foi inicialmente registrado como "Em análise". Em seguida existe um registro de "Aprovado" e logo na sequência "Aguardando Pagamento". Isso não faz muito sentido para mim e poderia ser um erro do próprio PagBank (?).
![image](https://github.com/user-attachments/assets/7a9d6b20-b4c0-4dd2-998d-fe4ab78101b2)

**Comment by eliasjnior** [comment]
Olá, @tiago-123 . O problema ainda existe?

Peço que caso tenha algum tipo de problema, abra um ticket de suporte em https://wordpress.org/support/plugin/pagbank-for-woocommerce, pois é o nosso canal oficial de suporte para o plugin.

Att.
